blogging/urls.py
from django.urls import path
from blogging.views import PostListView, PostDetailView, about_view, add_post

urlpatterns = [
    path("", PostListView.as_view(), name="blog_index"),
    path("add_post/", add_post, name="add_post"),
    path("posts/<int:pk>/", PostDetailView.as_view(), name="blog_detail"),
    path("about/", about_view, name="blog_about"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from users import views as user_views

urlpatterns = [
    path("", include("blogging.urls")),
    path("polling/", include("polling.urls")),
    path("admin/", admin.site.urls),
    path("login/", LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(template_name="logout.html"), name="logout"),
    path("register/", user_views.register, name="register"),
]

polling/urls.py
from io import DEFAULT_BUFFER_SIZE
from django.urls import path
from polling.views import PollListView, PollDetailView, create_poll

urlpatterns = [
    path("", PollListView.as_view(), name="poll_index"),
    path("polls/<int:pk>/", PollDetailView.as_view(), name="poll_detail"),
    path("post/", create_poll, name="create_poll"),
]

blogging/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    title = models.CharField(max_length=128)
    text = models.TextField(blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    published_date = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.title.title()


class Category(models.Model):
    name = models.CharField(max_length=128)
    description = models.TextField(blank=True)
    posts = models.ManyToManyField(Post, blank=True, related_name="categories")

    def __str__(self):
        return self.name.title()

    class Meta:
        verbose_name_plural = "Categories"

polling/models.py
from django.db import models


class Poll(models.Model):
    title = models.CharField(max_length=128)
    text = models.TextField(blank=True)
    score = models.IntegerField(default=0)

    def __str__(self):
        return self.title

users/models.py
from django.db import models

# Create your models here.

blogging/forms.py
from django.forms import ModelForm
from django.utils.translation import gettext_lazy as _
from blogging.models import Post, Category


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ["title", "text"]
        help_texts = {
            "title": _("Max length = 128 characters"),
        }


class CategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = ("name",)
        labels = {
            "name": _("Category"),
        }

polling/forms.py
from django.forms import ModelForm
from polling.models import Poll


class PollForm(ModelForm):
    class Meta:
        model = Poll
        fields = ["title", "text"]

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

blogging/views.py
from django.db.models.query import QuerySet
from django.shortcuts import render, redirect
from django.template import loader
from django.http import HttpResponse
from blogging.models import Post
from django.http import Http404
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from blogging.forms import PostForm, CategoryForm
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


@login_required
def add_post(request):
    if request.method == "POST":
        post_form = PostForm(request.POST)
        category_form = CategoryForm(request.POST)
        if post_form.is_valid() and category_form.is_valid():
            category = category_form.save()
            post = post_form.save(commit=False)
            post.author = request.user
            post.created_date = timezone.now()
            post.published_date = timezone.now()
            post.save()
            category.posts.add(post)

            return redirect("/")
    else:
        post = PostForm()
        category = CategoryForm()
        return render(request, "blogging/add_post.html", {"forms": [post, category]})


@method_decorator(login_required, name="dispatch")
class PostListView(ListView):
    queryset = Post.objects.exclude(published_date__exact=None).order_by(
        "-published_date"
    )
    post = queryset
    template_name = "blogging/list.html"


@method_decorator(login_required, name="dispatch")
class PostDetailView(DetailView):
    queryset = Post.objects.exclude(published_date__exact=None)
    published = queryset
    template_name = "blogging/detail.html"


def about_view(request):
    description = """This blog was created using the Django web framework by Eric Hoyle as 
    the culmination of a year long study of python programming through the UW 
    Professional and Continuing Education Programming in Python certificate
    course.
    """
    context = {"description": description}
    return render(request, "blogging/about.html", context)

polling/views.py
from django.contrib.auth import login
from django.shortcuts import render, redirect
from django.http import Http404
from polling.models import Poll
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from polling.forms import PollForm


@login_required
def create_poll(request):
    if request.method == "POST":
        poll_form = PollForm(request.POST)
        if poll_form.is_valid():
            poll_form.save()
            return redirect("/polling/")
    else:
        poll_form = PollForm()
        return render(request, "polling/create_poll.html", {"form": poll_form})


@method_decorator(login_required, name="dispatch")
class PollListView(ListView):
    model = Poll
    template_name = "polling/list.html"


@method_decorator(login_required, name="dispatch")
class PollDetailView(DetailView):
    model = Poll
    template_name = "polling/detail.html"

    def post(self, request, *args, **kwargs):
        poll = self.get_object()

        if request.POST.get("vote") == "Yes":
            poll.score += 1
        else:
            poll.score -= 1
        poll.save()

        context = {
            "poll": poll,
            "title": poll.title,
        }
        return render(request, "polling/detail.html", context)


# Create your views here.

users/views.py
from django.shortcuts import render, redirect

from django.contrib import messages
from .forms import UserRegisterForm


def register(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            messages.success(request, f"Account created for {username}")
            return redirect("blog_index")

    else:
        form = UserRegisterForm()
    return render(request, "users/register.html", {"form": form})

blogging/templates/blogging/about.html
{% extends "base.html" %}

{% block content %} 
<h2>About Django Blog</h2>
{{  description }}
{% endblock %}

blogging/templates/blogging/add_post.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Create a New Post</legend>
            {%for form in forms %}
            {{ form|crispy }}
            {% endfor %}
        </fieldset>

    <div class="form-group">
        <button class="btn btn-primary">Create Post</button>
    </div>
</div>
    </form>
{% endblock content %} 

blogging/templates/blogging/detail.html
{% extends "base.html" %}

{% block content %}
<a class="backlink" href ="/">Home</a>
<h1>{{ post }}</h1>
<p class="byline">
    Posted by {{ post.author.username }} &mdash; {{ post.published_date }}
</p>
<div class ="post-body">
    {{ post.text }}
</div>
<p>

<ul class="categories">
    Categories:
    {% for category in post.categories.all %}
        <li>{{ category }}</li>
    {% endfor %}
</ul>
</p>
{% endblock %}

blogging/templates/blogging/list.html
{% extends "base.html" %}{% block content %}
  <h1>Most Recent Posts</h1>
  {% comment %} here is where the query happens {% endcomment %}
  {% for post in post_list %}
  <div class="post">
    <h4>
      <a href="{% url 'blog_detail' post.pk %}" style="color: rgb(92, 155,  222)">{{ post }}</a>
    </h4>
    <p class="byline">
      Posted by {{ post.author.username }} &mdash; {{ post.published_date }}
    </p>
    <div class="post-body">
      {{ post.text }}
    </div>
    <div class="category_list">
      <p>
      <ul class="categories">
        Categories:
      {% for category in post.categories.all %}
        <li> {{ category }}</li>
      {% endfor %}
      </ul>
      </p>
    </div>
    </ul>

  </div>
  {% endfor %}
{% endblock %}

mysite/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <link rel="shortcut icon" href="{% static 'favicon3.png' %}"/>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
   
        {% if title %}
            <title>Django Blog - {{ title }}</title>
        {% else %}
            <title>Django Blog</title>
        {% endif %}
        <link type="text/css" rel="stylesheet" href="{% static 'django_blog.css' %}">
    </head>
    <body>
        <div id="header">  {# header begins here #}
        <img src="{% static 'favicon3.png' %}" alt="logo" class = "logo", width="97", height="97">
            <ul id="control-bar">
            <h1>Django Blog</h1>
            {% if user.is_authenticated %}
                <li><a href="{% url 'blog_index' %}">Home</a></li>
                <li><a href="{%url 'add_post' %}">Create Post</a></li>
                <li><a href="{% url 'poll_index' %}">Polls</a></li>
                <li><a href="{% url 'create_poll' %}">Create Poll</a></li>
                <li><a href="{% url 'logout' %}">Logout</a></li>
            {% if user.is_staff %}
                <li><a href="{% url 'admin:index' %}">Admin</a></li>{% endif %}
            {% else %}
                <li><a href="{% url 'login' %}">Login</a></li>
                <li><a href="{% url 'register' %}">Register</a></li> 
                <li><a href="{% url 'blog_about' %}">About</a></li>
              
            {% endif %}
            </ul>
        </div>      
  </div>             
            <div id="container">
            <div id="content" class="col-md-4">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
                {% block content %}
                [content will go here]
                {% endblock content %}
            </div>
        </div>
        
        </body>
    </body>

</html>

mysite/templates/login.html
{% extends "base.html" %}

{% block content %}
<h1>My Blog Login</h1>
<form action="" method="POST">{% csrf_token %}
  {{ form.as_p }}
  <p><input type="submit" value="Log In"></p>
  <small class="text-muted">
    Don't Have an Account? <a class="ml-2" href="{% url 'register' %}">Register</a>
</small>
</form>
{% endblock %}

mysite/templates/logout.html
{% extends "base.html" %}
{% block content %}
<h1>Logout Successful</h1>
{% endblock content %}

polling/templates/polling/create_poll.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Create a New Poll</legend>
            {{ form|crispy }}
        </fieldset>

    <div class="form-group">
        <button class="btn btn-primary">Create Poll</button>
    </div>
</div>
    </form>
{% endblock content %}

polling/templates/polling/detail.html
{% extends "base.html" %}
{% block content %}
<h1>{{ poll.title }}</h1>
<div class="poll-body">
    {{ poll.text }}
</div>
<div class="poll-score">
    current score: {{ poll.score }}
</div>
<div class="poll-vote">
    <form method="POST">
        {% csrf_token %}
        <input type="submit" name="vote" value="Yes">
        <input type="submit" name="vote" value="No">
    </form>
</div>
{% endblock content %}

polling/templates/polling/list.html
{% extends "base.html" %}
{% block content %}
<h1> Polls</h1>
{% for poll in poll_list %}
    <div class="poll">
        <h2>
            <a href="{% url 'poll_detail' poll.pk %}">{{ poll.title }}</a>
        </h2>
    </div>
{% endfor %}
{% endblock %}

users/templates/users/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Join Today</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
                <button class="btn btn-outline-info" typ="submit">Sign Up</button>
        </div>
    </form>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already Have an Account? <a class="ml-2" href="{% url 'login' %}">Sign In</a>
        </small>
    </div>
</div>
{% endblock %}